# Generated by Django 4.2.30 on 2026-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID of the final failed attempt', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Exception message from the last retry')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times the task was attempted before giving up')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed Email Task',
                'verbose_name_plural': 'Failed Email Tasks',
                'ordering': ['-failed_at'],
            },
        ),
    ]
